name: GCP Google Cloud Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  gcp-deploy-pipeline:
    runs-on: ubuntu-latest

    # Injecting the variables required by main.tf here 👇
    env:
      TF_VAR_project:      ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_network_name: ${{ secrets.GCP_NETWORK_NAME }}
      TF_VAR_subnet_cidr:  ${{ secrets.GCP_SUBNET_CIDR }}
      TF_VAR_region:       ${{ secrets.GCP_REGION }}

    steps:
    - name: Checkout Repository Source Code
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud via Keyless WIF'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "latest"

    - name: 'Terraform Init'
      run: terraform init -input=false -backend-config="bucket=${{ secrets.GCS_STATE_BUCKET }}" -backend-config="prefix=${{ secrets.GCS_STATE_PREFIX }}"

    # Runs on Pull Request: Will use the env variables above automatically
    - name: 'Terraform Plan'
      if: github.event_name == 'pull_request'
      run: terraform plan -input=false

    # Runs on Merge to Main: Will use the env variables above automatically
    - name: 'Terraform Apply'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -input=false -auto-approve